name: Release

'on':
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm install semantic-release @traverson/semantic-release-config --no-save
      - name: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
